networks:
  graphbuilder-network:
    name: graphbuilder-network
    driver: bridge
    external: true

volumes:  
  graphbuilder-data:


services:
  graphbuilder:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - graphbuilder-network
    ports:
      - "8000:8000"
    environment:
      - DATA_DIR=/app/data
    volumes:
      - graphbuilder-data:/app/data
    command: python run_pipeline.py
